//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "distributions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub pool_id: Uuid,
    pub miner_id: Uuid,
    pub worker_id: Uuid,
    pub reward: i64,
    #[sea_orm(column_type = "Decimal(Some((3, 32)))")]
    pub hashrate_external: Decimal,
    #[sea_orm(column_type = "Decimal(Some((3, 32)))")]
    pub hashrate_internal: Decimal,
    pub date: Date,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::miners::Entity",
        from = "Column::MinerId",
        to = "super::miners::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Miners,
    #[sea_orm(
        belongs_to = "super::pools::Entity",
        from = "Column::PoolId",
        to = "super::pools::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Pools,
    #[sea_orm(
        belongs_to = "super::workers::Entity",
        from = "Column::WorkerId",
        to = "super::workers::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Workers,
}

impl Related<super::miners::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Miners.def()
    }
}

impl Related<super::pools::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Pools.def()
    }
}

impl Related<super::workers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
