# Error Tracking Stack for Loka Stratum
# Alternative to Sentry using Prometheus + Grafana + AlertManager

version: '3.8'

services:
  # Loki for log aggregation (lightweight alternative to ELK)
  loki:
    image: grafana/loki:2.9.0
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki-data:/tmp/loki
    networks:
      - loka-monitoring-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Promtail for log collection
  promtail:
    image: grafana/promtail:2.9.0
    restart: unless-stopped
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - ./loki/promtail-config.yaml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - loka-monitoring-network
    depends_on:
      - loki

  # Error tracking service (custom)
  error-tracker:
    image: prom/pushgateway:v1.6.2
    restart: unless-stopped
    ports:
      - "9091:9091"
    networks:
      - loka-monitoring-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9091/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  loki-data:
    driver: local

networks:
  loka-monitoring-network:
    external: true