apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 2.48.0
      cacheLevel: 'High'
      timeInterval: 15s
      queryTimeout: 60s
      defaultRegion: us-east-1
      customQueryParameters: ''
      manageAlerts: true
      alertmanagerUid: alertmanager
    secureJsonData: {}
    uid: prometheus
    version: 1

  - name: AlertManager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    isDefault: false
    editable: true
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: true
    uid: alertmanager
    version: 1

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: prometheus
          matcherRegex: 'traceID=(\w+)'
          name: TraceID
          url: '$${__value.raw}'
    uid: loki
    version: 1