# Loka Stratum Configuration File
# This file contains default configuration for the Loka Stratum mining proxy

[server]
# Server binding configuration
bind_address = "0.0.0.0:3333"
# Maximum concurrent connections
max_connections = 1000
# Connection timeout in seconds
connection_timeout = 30

[server.idle_timeout]
secs = 300
nanos = 0

[server.pool]
address = "130.211.20.161:9200"
name = "nicehash"
username = "37vuX2XMqtcrobGwxSZJSwJoYyjiH18SiQ"
password = "x"
separator = [".", "_"]
extranonce = false

[pool]
address = "130.211.20.161:9200"
name = "nicehash"
username = "37vuX2XMqtcrobGwxSZJSwJoYyjiH18SiQ"
password = "x"
separator = [".", "_"]
extranonce = false

[limiter]
connections = 1000

[limiter.jobs]
secs = 600
nanos = 0

[limiter.submissions]
secs = 172800
nanos = 0

[metrics]
# Metrics HTTP server configuration
enabled = true
bind_address = "0.0.0.0:9090"
# Metrics collection interval in seconds
interval = 5
# Export format (json, prometheus)
export_format = "both"

[logging]
# Logging configuration
level = "info"
# Log format (json, text)
format = "json"
# Enable structured logging
structured = true

[performance]
# Performance optimization settings
worker_threads = 8
# String pool configuration
string_pool_size = 10000
# Cache settings
cache_ttl = 300
cache_max_size = 1000

[security]
# Security configuration
rate_limit = 100
# Enable CORS for metrics endpoint
enable_cors = true
# IP filtering (whitelist/blacklist)
ip_filter_mode = "none"

[monitoring]
# Monitoring and alerting
health_check_interval = 30
# Alert thresholds
cpu_threshold = 80.0
memory_threshold = 80.0
error_rate_threshold = 10.0

# Environment variable overrides
# These settings can be overridden by environment variables:
# POOL_ADDRESS, RUST_LOG, LOKA_MAX_CONNECTIONS, etc.