name: Build loka-stratum

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev curl

      - name: Build loka-stratum
        run: |
          cd stratum
          cargo build --release

      - name: List build outputs
        run: |
          echo "=== Build directory contents ==="
          ls -la target/release/
          echo "=== Binary details ==="
          file target/release/loka-stratum

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: loka-stratum
          path: target/release/loka-stratum
